Repository opencypher/cypher-for-gremlin, pull requests merged in 2018-04, with the labels that each got.

#31 Remove unused aliases
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CastTest.java
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFilters.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveImmediateReselect.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliases.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
  translation/src/test/java/org/opencypher/gremlin/translation/helpers/CypherAstAssert.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/RemoveImmediateReselectTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliasesTest.java
Labels: enhancement

#32 Minor code clean up
  translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/context/StatementContext.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/CreateWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/DeleteWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/MatchWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/MergeWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/RelationshipPatternWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/SetWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/StatementWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/UnwindWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
Labels: refactoring

#33 Inline mapped traversals
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFilters.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/InlineMapTraversal.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/InlineMapTraversalTest.java
Labels: enhancement

#30 Descriptive error in case of wrong serializer
  translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java
Labels: enhancement

#37 Implementation for 'properties'
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
  translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
Labels: enhancement

#40 UNWIND keys() translation
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/UnwindTest.java
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/UnwindWalker.scala
Labels: enhancement

#41 Fail fast on unsupported expression
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
Labels: bug

#44 Percentile functions
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/PercentileTest.java
  testware/tck/src/test/scala/org/opencypher/gremlin/tck/GremlinErrors.scala
  translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
Labels: enhancement

#46 Remove optimizations from projection walker
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ListComprehensionTest.java
  translation/src/main/java/org/opencypher/gremlin/translation/Tokens.java
  translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/CosmosDbFlavorTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/InlineMapTraversalTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/RemoveImmediateReselectTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/RemoveUnusedAliasesTest.java
Labels: refactoring

#50 Simplify statement walker
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/StatementWalker.scala
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/InlineMapTraversalTest.java
Labels: refactoring

#51 Link to pre-configured Gremlin Console
  README.md
  tinkerpop/cypher-gremlin-console-plugin/README.md
Labels: documentation

#54 Re-use expression walker in writing clauses
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CreateTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/NullTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySetters.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/CreateWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/SetWalker.scala
  translation/src/test/java/org/opencypher/gremlin/translation/helpers/CypherAstHelpers.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySettersTest.java
Labels: enhancement

#55 Model collection literals as projections
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ContainerIndexTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CreateTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/DeleteTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/LiteralTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/NativeTraversalTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WithTest.java
  translation/src/main/java/org/opencypher/gremlin/translation/groovy/StringTranslationUtils.java
  translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
  translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/context/StatementContext.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySetters.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/CreateWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/DeleteWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/NodeUtils.scala
  translation/src/test/java/org/opencypher/gremlin/translation/helpers/CypherAstHelpers.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/GroupStepFiltersTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/SimplifyPropertySettersTest.java
Labels: enhancement

#57 Projection Simplifications rewriter
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/ProjectionSimplifications.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/translator/TranslatorFlavor.scala
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/ProjectionSimplificationsTest.java
Labels: enhancement

#58 Fix TCK regression
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/ProjectionSimplifications.scala
Labels: bug

#59 Update language support notes
  README.md
Labels: documentation

#69 Gremlin translation of ContainerIndex
  translation/src/main/java/org/opencypher/gremlin/translation/GremlinSteps.java
  translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java
  translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java
  translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java
  translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/builder/IRGremlinSteps.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/model/GremlinStep.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ExpressionWalker.scala
Labels: enhancement
