Repository opencypher/cypher-for-gremlin, pull requests merged in 2018-03, with the labels that each got.

#6 RHS improvements
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ComplexExamplesTest.java
  translation/src/main/java/org/opencypher/gremlin/translation/Tokens.java
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
  translation/src/test/java/org/opencypher/gremlin/translation/MatchTest.java
Labels: enhancement

#8 Test migration from translation to integration
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ComplexExamplesTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/LiteralTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/MatchTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/MergeTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/OptionalMatchTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WhereTest.java
  testware/testware-common/src/main/resources/modern.cyp
  translation/src/test/java/org/opencypher/gremlin/translation/MatchTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/MergeTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/OptionalMatchTest.java
Labels: refactoring

#12 Migrate LiteralTest from translation to integration
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/LiteralTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
  translation/src/main/java/org/opencypher/gremlin/translation/groovy/StringTranslationUtils.java
  translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java
  translation/src/test/java/org/opencypher/gremlin/translation/LiteralTest.java
Labels: refactoring

#16 Handle constants in WHERE lhs
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WhereTest.java
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
Labels: enhancement

#17 Optimize match adjacency of WHERE
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WhereTest.java
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/GremlinRewriter.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/PropertyMatchAdjacency.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/Rewriting.scala
  translation/src/test/java/org/opencypher/gremlin/translation/RewriterTest.java
  translation/src/test/java/org/opencypher/gremlin/translation/helpers/CypherAstHelpers.java
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/PropertyMatchAdjacencyTest.java
  translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RewritingTest.scala
Labels: enhancement

#18 Rewrite WHERE predicates separately by projection
  translation/src/main/scala/org/opencypher/gremlin/translation/CypherAst.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/FilterStepAdjacency.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/rewrite/Rewriting.scala
  translation/src/test/java/org/opencypher/gremlin/translation/ir/rewrite/FilterStepAdjacencyTest.java
  translation/src/test/scala/org/opencypher/gremlin/translation/ir/rewrite/RewritingTest.scala
Labels: enhancement

#19 Fix for parameter use in containter index
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ParameterTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WithTest.java
  translation/src/main/scala/org/opencypher/gremlin/translation/ir/TranslationWriter.scala
Labels: bug

#22 Support function invocations in WHERE rhs
  README.md
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WhereTest.java
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
Labels: enhancement

#23 Native gremlin translation of path
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ReturnTest.java
  translation/src/main/java/org/opencypher/gremlin/translation/Tokens.java
  translation/src/main/java/org/opencypher/gremlin/traversal/CustomFunction.java
  translation/src/main/java/org/opencypher/gremlin/traversal/ReturnNormalizer.java
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/MatchWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/ProjectionWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/RelationshipPatternWalker.scala
  translation/src/main/scala/org/opencypher/gremlin/translation/walker/WhereWalker.scala
Labels: refactoring

#25 Bytecode translation with query parameters
  build.gradle
  testware/integration-tests/src/test/java/org/opencypher/gremlin/client/BytecodeCypherGremlinClientTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/groups/SkipWithBytecode.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CastTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ContainerIndexTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/CreateTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ListComprehensionTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/NativeTraversalTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/ParameterTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/SetTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/UnionTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WhereTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/queries/WithTest.java
  testware/integration-tests/src/test/java/org/opencypher/gremlin/snippets/Translation.java
  testware/testware-common/src/main/java/org/opencypher/gremlin/rules/GremlinServerExternalResource.java
  tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/BytecodeCypherGremlinClient.java
  tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/CypherGremlinClient.java
  tinkerpop/cypher-gremlin-server-client/src/main/java/org/opencypher/gremlin/client/TraverserIterator.java
  tinkerpop/cypher-gremlin-server-plugin/src/main/java/org/opencypher/gremlin/server/jsr223/CypherPlugin.java
  translation/README.md
  translation/src/main/java/org/opencypher/gremlin/translation/GremlinPredicates.java
  translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinBindings.java
  translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinPredicates.java
  translation/src/main/java/org/opencypher/gremlin/translation/bytecode/BytecodeGremlinSteps.java
  translation/src/main/java/org/opencypher/gremlin/translation/groovy/GroovyGremlinSteps.java
  translation/src/main/java/org/opencypher/gremlin/translation/groovy/StringTranslationUtils.java
  translation/src/main/java/org/opencypher/gremlin/translation/translator/Translator.java
  translation/src/main/java/org/opencypher/gremlin/translation/traversal/TraversalGremlinSteps.java
  translation/src/main/java/org/opencypher/gremlin/traversal/CustomPredicate.java
  translation/src/main/java/org/opencypher/gremlin/traversal/CustomPredicates.java
  translation/src/test/java/org/opencypher/gremlin/traversal/CustomPredicateTest.java
  translation/src/test/java/org/opencypher/gremlin/traversal/CustomPredicatesTest.java
Labels: enhancement
